# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sören Oehding
title: Lead Developer @Mondia Group
email: soeren.oehding@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: soeren.oehding.de
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username: s-oehding
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: soehding
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0003-3511-7121
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
  - title: Strava
    icon: fa-brands fa-strava
    url: https://www.strava.com/athletes/31512898

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-54WBNR4"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
# about_content: | # this will include new lines to allow paragraphs
#   I'm a fullstack software engineer specializing in building and designing distributed services. Big passion for Devops culture and 'you build it you run it' methodology. I like to inspire other developers to not only develop but also own and maintain their projects. To think outside the box and not be afraid of what comes after the development phase. It doesn't just run on your machine and everyone should understand what happens after ;)
about_content: | # this will include new lines to allow paragraphs
    I'm a fullstack software engineer specializing in building and designing distributed services. I like to think outside the box and discover and learn new things on a frequent basis. 
content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  # - layout: left
  #   border: # Value of `weak` will display a weak border below this item.
  #   title: Monsooq
  #   link: https://monsooq.com?x-mm-debug=true
  #   link_text: monsooq.com
  #   additional_links:
  #     - title: Github page for project (eg. sproogen/modern-resume-theme)
  #       icon: fab fa-github
  #       url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #     - title: Github page for project (eg. sproogen/modern-resume-theme)
  #       icon: fab fa-github
  #       url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #   quote: >
  #     Short overview of the project (optional)
  #   description: | # this will include new lines to allow paragraphs
  #     Description about the work on/with the project
  - title: Experience
    layout: timeline
    content:
      - layout: left
        title: Mondia Group
        sub_title: Senior Fullstack Developer</br>
        caption: [Lead Developer]
        daterange: 03/2020 - present
        link: mondia.com
        quote: >
          Mondia, through its three businesses Mondia Pay, Mondia Digital and Mondia Innovation provides access to over 1.5bn consumers through more than 85+ mobile operators across 75+ countries.
        description: | # this will include new lines to allow paragraphs
          **RESPONSIBILITIES:**<br>
          Took over new team lead role on Mondias new marketplace solution Monsooq.com.  
          Development of a solid and scalable Frontend solution based on Vue.js.  
          Development of the Monsooq Backend which is powered by MongoDB, HapiJs and GraphQL.  
          Hiring and leading a remote Team of developers based in Kiev started in 2021.  

          **TECHSTACK:**<br>
          <mark>JavaScript</mark> <mark>node</mark> <mark>babel</mark> <mark>webpack</mark>
          <mark>Vuejs</mark> <mark>graphQL</mark> <mark>MongoDB</mark> <mark>Docker</mark>
          <mark>Jenkins</mark> <mark>Nomad</mark> <mark>Consul</mark> <mark>Traefik</mark>

      - layout: left
        title: Mondia Group
        sub_title: Senior Frontend Developer
        caption:
        daterange: 03/2019 - 03/2020
        link: mondia.com
        quote:
        description: | # this will include new lines to allow paragraphs
          **RESPONSIBILITIES:**<br>
          Development of a boilerplate based on Vue.j s and Hapi.js for quick development of internal tools.
          Maintenance and further development of existing internal administration tools.
          Assistance in the implementation of Hashicorp Nomad / Hashi stack as deployment solution.
          Creation of Jenkins CI / CD pipelines and Jenkins shared libraries

          **TECHSTACK:**<br>
          <mark>JavaScript</mark> <mark>node</mark> <mark>babel</mark> <mark>webpack</mark>
          <mark>Vuejs</mark> <mark>graphQL</mark> <mark>MongoDB</mark> <mark>Docker</mark>
          <mark>Jenkins</mark> <mark>Nomad</mark> <mark>Consul</mark> <mark>Traefik</mark>
      - layout: left
        title: WERK4 NEUE MEDIEN
        sub_title: Web Developer
        caption:
        daterange: 10/2017 - 03/2019
        link: werk4.net
        quote: >
          Werk4 evolved from a traditional advertising agency to an award-winning hybrid agency. The cross-border and valuable thinking of their top-trained staff delivers creative solutions across all media channels.
        description: | # this will include new lines to allow paragraphs
          **RESPONSIBILITIES:**<br>
          Development of web applications and corporate websites.
          Development / provision of Docker based internal development environments.
          Maintenance and further development of existing customer projects.
          Customer training after project handover care and maintenance of in-house IT.

          **TECHSTACK:**<br>
          <mark>JavaScript</mark> <mark>node</mark> <mark>babel</mark> <mark>webpack</mark> <mark>Sass/Less</mark>
          <mark>Vuejs</mark> <mark>Nuxt</mark> <mark>MySQL</mark>  <mark>Docker</mark>
          <mark>PHP</mark> <mark>Wordpress</mark> <mark>Neos</mark> <mark>Symfony</mark>
      - layout: left
        title: GRES SPANIENFLIESEN
        sub_title: Frontend Developer
        caption:
        daterange: 10/2015 - 02/2017
        link: spanienfliesen.de
        quote:
        description: | # this will include new lines to allow paragraphs
          **RESPONSIBILITIES:**<br>
          Frontend development for Shopware based online shops.
          Development of Shopware plugins.
          Connecting the online shops to ERP systems and interfaces to shipping and payment service providers.
          Training of student assistants for product maintenance.
          Supervision and design of WordPress Landingpages

          **TECHSTACK:**<br>
          <mark>JavaScript</mark> <mark>gulp</mark> <mark>Vagrant</mark> <mark>Sass/Less</mark>
          <mark>PHP</mark> <mark>MySQL</mark> <mark>Wordpress</mark> <mark>Magento</mark>
      - layout: left
        title: INNOVATIVE TRAINING SYSTEMS
        sub_title: Frontend Developer
        caption:
        daterange: 04/2013 - 10/2015
        link: suprfit.com
        quote:
        description: | # this will include new lines to allow paragraphs
          **RESPONSIBILITIES:**<br>
          Frontend development for Magento based online shops B2B and B2C.
          Connecting the online shops to ERP systems and interfaces to shipping and payment service providers.
          Supervision / design WordPress.

          **TECHSTACK:**<br>
          <mark>JavaScript</mark> <mark>gulp</mark> <mark>Sass/Less</mark>
          <mark>PHP</mark> <mark>MySQL</mark> <mark>Wordpress</mark> <mark>Magento</mark>
  - title: Education
    layout: timeline
    content:
      - layout: top-left
        title: Diploma FH Nordhessen
        sub_title: "-"
        caption:
        daterange: 12/2014 - 12/2018
        quote:
        description: | # this will include new lines to allow paragraphs
          GRAPHICS & DESIGN - FOCUS ON DIGITAL APPLICATIONS
      - layout: top-left
        title: SAE Hamburg
        sub_title: Diploma
        caption:
        daterange: 06/2006 - 12/2009
        quote:
        description: | # this will include new lines to allow paragraphs
          AUDIO ENGINEERING & DIGITAL MEDIA

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      <div class="row">
        <div class="col-xs-12 col-md-6 content">
          <p>
          When i'm not at work or otherwise in front of the computer you can find me ideally on the road bike or gravel bike on tour through nature, the further out the better :)
          If the weather does not play along, I tinker with pet projects or home automation around<br>
          </p>
        </div>
        <div class="col-xs-12 col-md-6">
          <img src="images/bike.jpg" />
          <iframe height='auto' width='100%' style="min-height: 200px; margin-top: 2rem;" frameborder='0' allowtransparency='true' scrolling='no' src='https://www.strava.com/athletes/31512898/activity-summary/7dee0c0f16d353e312cf41df8ab76c4f43387085'></iframe>
          </div>
      </div>
# Footer
footer_show_references: true
references_title: References on request

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
